name = "radartips-api"
main = "src/index.js" # ou src/index.ts / src/worker.js (use o que seu projeto usa)
compatibility_date = "2026-02-03"

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "RADAR_LIVE"
id = "7985bdade9df416690cfd0226ebd78d2"
