name = "radartips"
main = "src/index.js"
compatibility_date = "2026-02-03"

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "RADARTIPS_LIVE"
id = "7985bdade9df416690cfd0226ebd78d2"

[[r2_buckets]]
binding = "R2"
bucket_name = "radartips-data"

# Route configuration: mount Worker at /api/* on custom domain
[[routes]]
pattern = "radartips.com/api/*"
zone_name = "radartips.com"

[[routes]]
pattern = "www.radartips.com/api/*"
zone_name = "radartips.com"
